language: node_js
node_js:
- '6'

sudo: required
dist: trusty

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

install:
- curl -sSL "https://get.docker.com/gpg" | sudo -E apt-key add -
- echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" |
  sudo tee -a /etc/apt/sources.list
- sudo apt-get update
- sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --assume-yes install docker-engine
- sudo pip install docker-compose

before_script:
- chmod +x ./volume/init.sh
- "./volume/init.sh test test data/"
- docker-compose -f docker-compose.yml -f docker-compose.test.yml up --build -d
- sleep 10

script:
- docker exec --privileged -it app npm test

after_script:
- docker-compose down
- docker volume rm $(docker volume ls -qf dangling=true)

after_success:
- sudo docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
- export REPO_APP=alta0815/wikiorg
- export REPO_DB=alta0815/mongo
- export REPO_NGINX=alta0815/nginx
- export TAG=latest
- sudo docker build -t $REPO_APP:$COMMIT .
- sudo docker tag $REPO_APP:$COMMIT $REPO_APP:$TAG
- sudo docker push $REPO_APP
- sudo docker build -t $REPO_DB:$COMMIT ./db
- sudo docker tag $REPO_DB:$COMMIT $REPO_DB:$TAG
- sudo docker push $REPO_DB
- sudo docker build -t $REPO_NGINX:$COMMIT ./nginx
- sudo docker tag $REPO_NGINX:$COMMIT $REPO_NGINX:$TAG
- sudo docker push $REPO_NGINX