version: '2'
services: 
  nginx:
    volumes:
      - ./nginx/public/:/var/www/public/
    depends_on:
      - app
  app:
    environment:
      - NODE_ENV=development
    env_file:
      db/auth/dev.env
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db